# Generated by Django 2.1.2 on 2020-06-09 18:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('genero', models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('PN', 'Prefiero no contestar')], max_length=15, null=True, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha Nacimiento')),
                ('foto', models.ImageField(max_length=500, null=True, upload_to='imagenes', verbose_name='Foto')),
                ('check_terminos', models.BooleanField(null=True, verbose_name='Acepta terminos')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('email', models.CharField(max_length=80, verbose_name='Email')),
                ('mensaje', models.CharField(max_length=300, verbose_name='Mensaje')),
                ('respondido', models.BooleanField(verbose_name='Respondido')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('destinatario', models.IntegerField(verbose_name='Destinatario')),
                ('cantidad', models.FloatField(max_length=4, verbose_name='Cantidad')),
                ('fecha_pago', models.DateField(verbose_name='Fecha pago')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('origen', models.CharField(max_length=80, verbose_name='Origen')),
                ('destino', models.CharField(max_length=80, verbose_name='Destino')),
                ('fecha_salida', models.DateField(verbose_name='Fecha')),
                ('hora_recogida', models.TimeField(verbose_name='Hora recogida')),
                ('hora_llegada', models.TimeField(verbose_name='Hora llegada')),
                ('num_pasajeros', models.IntegerField(default=0, verbose_name='Num. Plazas')),
                ('asiento_libre', models.IntegerField(default=0, verbose_name='Num. Plazas libres')),
                ('precio_plaza', models.FloatField(max_length=4, verbose_name='Precio')),
                ('check_carne', models.BooleanField(verbose_name='Carné conducir')),
                ('activo', models.IntegerField(default=1, verbose_name='Activo')),
                ('borrado', models.IntegerField(default=0, verbose_name='Borrado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('matricula', models.CharField(max_length=7, verbose_name='Matricula')),
                ('modelo', models.CharField(max_length=10, verbose_name='Modelo')),
                ('activo', models.IntegerField(default=1, verbose_name='Activo')),
                ('borrado', models.IntegerField(default=0, verbose_name='Borrado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='trayecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appjobcar.Trayecto', verbose_name='Trayecto'),
        ),
    ]
